repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-merge-conflict
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: '0.28.5'
  hooks:
  - id: check-dependabot
    args: ["--verbose"]
  - id: check-github-actions
    args: ["--verbose"]
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.4
  hooks:
  - id: actionlint
