repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-merge-conflict
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: '0.28.5'
  hooks:
  - id: check-dependabot
    args: ["--verbose"]
  - id: check-github-actions
    args: ["--verbose"]
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: v1.7.1.15
  hooks:
  - id: actionlint
    additional_dependencies: [ pyflakes>=3.0.1, shellcheck-py>=0.9.0.5 ]
