on:
  workflow_call:
jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - name: self test action
      uses: ./
