name: Publish Release
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}
jobs:
  create-release:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: softprops/action-gh-release@v2
      with:
        body: "Create release ${{ github.ref_name }}"
        make_latest: true
    - shell: bash
      run: |
        tag="${{ github.ref_name }}"
        if [[ "$tag" =~ ^v[0-9]+\. ]]; then
          branch_name="$(echo "$tag" | cut -d. -f 1)"
          git checkout -b "$branch_name" ${{ github.sha }}
          git push -f origin "$branch_name":"$branch_name"
        fi
